export enum actionTypes {
  CART_ADD_ITEM = 'CART_ADD_ITEM',
  CART_CLEAR = 'CART_CLEAR',
  CURRENCY_SELECTOR_UPDATE = 'CURRENCY_SELECTOR_UPDATE',
  CURRENCY_RATES_FETCH = 'CURRENCY_RATES_FETCH',
  PRODUCTS_FETCH = 'PRODUCTS_FETCH',
};